### ISSUE TITLE
DynamicMap only updates once

### ISSUE THREAD

**Issue by philippjfr** [holoviz/holoviews#2125]
In this simple example the plot only updates the first time the widget value is changed:

```python
macro = pd.read_csv('../data/macro.csv')
opts = vDimSize()
scatter = hv.Scatter(macro,'year',['growth','trade','unem'])
dmap = hv.DynamicMap(lambda **kwargs: scatter.opts(plot=kwargs), streams=[opts])
paramnb.Widgets(opts, callback=opts.event, continuous_update=True)
dmap
```

**Comment by jlstevens** [comment]
This issue has been bumped so many times! I'll optimistically assign it to 1.14.1

**Comment by jlstevens** [comment]
I think I'm going to close this issue because:

1. This was opened way back in 2017!
2. We now use panel, not `paramnb`
3. I'm not sure what `vDimSize` is supposed to be.

And mostly importantly: 

4. This modernized example of driving the dynamicmap with widgets works fine (the even and I think this is the sort of thing the issue was about):

![image](https://user-images.githubusercontent.com/890576/106488583-77489d00-6479-11eb-8ab9-1726cb33eefd.png)
