### ISSUE TITLE
Update Customizing Plots Docs

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#2916]
http://holoviews.org/user_guide/Customizing_Plots.html

Perhaps could deprecate the .opts() syntax in favor of the .options() because .opts() is very overwhelming, and demonstrate that it's possible to access specific elements with .options() `
.options({'VLine': dict(axiswise=True), 'Curve': dict(axiswise=True)})`

Also maybe prioritize .options() over %%opts since .options() is portable in notebook and py script.

I can help if wanted!

**Comment by jbednar** [comment]
Yes, .options() should replace .opts() in nearly every case, and probably eventually in every case.  I've already done that for pyviz.org, but holoviews.org needs it to.

I agree with preferring .options() over %%opts as well, but that's a larger task, because it often needs examples to be refactored rather than simply replaced.  %%opts has many differences from .options() that need very careful attention, such as whether they work in place or give a new object, the scope of what they affect, whether they apply per type or per object, etc.  So helping move the most important docs over to .options() would be a great service to us!

The main remaining benefit of %%opts is tab completion, but with some work that can be fixed too (https://github.com/ioam/holoviews/issues/2485).
