### ISSUE TITLE
Changing default HoloViews colormap

### ISSUE THREAD

**Issue by ahuang11** [holoviz/holoviews#3500]
Since the default cmap's highest value is white, it's hard to tell if the white values are the max or NaN without hover (and most colormaps used do not use gray?)

![image](https://user-images.githubusercontent.com/15331990/52905688-749fff00-31f2-11e9-84f3-567251b3b045.png)

**Comment by poplarShift** [comment]
+1, this makes sense to me. Either that or change the default cmap?

**Comment by jbednar** [comment]
I thought we already had an issue about various problems with the default colormap, but I was unable to find it by searching for "colormap" or "default" or "hot".  From what I remember, there are many reasons to change HoloViews' default "hot" colormap, given that the default page color is typically white for Jupyter notebooks:

1. "hot" is highly nonuniform perceptually as described at [colorcet.pyviz.org](colorcet.pyviz.org).
2. The peak value of the colormap is white, making it impossible to distinguish a NaN area from a peak value
3. The highest data values are those most similar to the page color, when for intuitive understanding of a sequentially ordered set of numeric values the highest values should be maximally different from the page color. (That way, isolated patches will be more visible the higher their value, but currently they have _less_ contrast as their values increase.)
4. (Less crucial) The lowest value in the colormap is black, which can be ambiguous with other data elements in the plot that default to black.

Possible improvements:

- It has been proposed to use "fire" instead, which addresses issue 1, but it still has the other three problems. To illustrate problems 2 and 3, with "fire" on a white background you get sharp perceptual discontinuities between low values and NaN values; it only really works on a black background:
![image](https://user-images.githubusercontent.com/1695496/53128464-7f2c0280-352a-11e9-813b-99fe6ad5a912.png)
![image](https://user-images.githubusercontent.com/1695496/53128484-88b56a80-352a-11e9-9a98-9648ea5399a1.png)
- The `linear_kry_5_98_c75` colormap in [colorcet](http://colorcet.pyviz.org/user_guide/index.html) is a version of fire that doesn't top out at white, avoiding problem 2, but it still has problems 3 and 4. 
- A reversed version of `linear_kry_5_98_c75` would avoid problems 1, 2, and 3, but it still has 4 (now at the top end) and also is a bit odd, as it uses colors from black-body radiation (like "hot" and "fire") but in an unintuitive order
- We could use viridis as matplotlib does now, solving problems 1, 2, and 4, but it still suffers from 3 in that isolated patches of high-value pixels are very similar to a white page color, instead of showing up very strongly as they should. Parula, gray, magma, inferno, and plasma all suffer from the same problem; people choosing these as good defaults seem not to have considered the issue of isolated pixels and small patches surrounded by NaNs. We can of course reverse any of these colormaps to solve problem 4, but that would be confusing to anyone who is used to seeing them in their native ordering.

Colormaps `bgy_r`, `bmy_r`, `dimgray_r`, `kbc_r`, and `kgy_r` from [colorcet](http://colorcet.pyviz.org/user_guide/index.html)?  would meet all the criteria above, but I don't know if anyone would be happy with those as a default.

**Comment by ahuang11** [comment]
I like RdYlBu_r, but it probably has its own issues with that being the default

**Comment by jbednar** [comment]
RdYlBu is a diverging colormap (see http://holoviews.org/user_guide/Colormaps.html), which is useful for plots with a well defined central value (e.g. deviations around a mean, or positive and negative values). Those conditions occur often, but more often a sequential colormap is appropriate, so I think the default needs to be sequential.

**Comment by poplarShift** [comment]
Thanks for this detailed post @jbednar ! Personally I like `bgy_r`, it is rather similar to viridis in overall appearance.

**Comment by jbednar** [comment]
I put together a simple notebook with examples of data plotted against the default white background, which is what matters for the default colormap: https://anaconda.org/jbednar/hv_colormap/notebook

In each one, notice how some data disappears if the colormap includes white, and also notice how the peak data is more intuitive and perceptible if the largest color value is most different from white.

![cmap_viridis_r](https://user-images.githubusercontent.com/1695496/61416074-67716400-a8a7-11e9-8b94-9163301a0ec3.png)
![cmap_viridis](https://user-images.githubusercontent.com/1695496/61416075-67716400-a8a7-11e9-9a77-935a289c3f8e.png)
![cmap_kbc_r](https://user-images.githubusercontent.com/1695496/61416076-6809fa80-a8a7-11e9-82de-5328bf580506.png)
![cmap_kbc](https://user-images.githubusercontent.com/1695496/61416077-6809fa80-a8a7-11e9-8def-f5357c09c0f7.png)
![cmap_gray_r](https://user-images.githubusercontent.com/1695496/61416078-6809fa80-a8a7-11e9-931d-df19d59f4e69.png)
![cmap_gray](https://user-images.githubusercontent.com/1695496/61416079-6809fa80-a8a7-11e9-8ec6-b97b56955fe6.png)
![cmap_fire_r](https://user-images.githubusercontent.com/1695496/61416080-6809fa80-a8a7-11e9-8ebb-4c9ed5e2cd1d.png)
![cmap_fire](https://user-images.githubusercontent.com/1695496/61416081-6809fa80-a8a7-11e9-8a12-f50c3be08e53.png)
![cmap_cet_linear_kry_5_98_c75_r](https://user-images.githubusercontent.com/1695496/61416082-68a29100-a8a7-11e9-8246-5b29af37a7d4.png)
![cmap_cet_linear_kry_5_98_c75](https://user-images.githubusercontent.com/1695496/61416083-68a29100-a8a7-11e9-851f-f25dd2cb22f5.png)
![cmap_bgy_r](https://user-images.githubusercontent.com/1695496/61416084-68a29100-a8a7-11e9-888a-f20843dc3e64.png)
![cmap_bgy](https://user-images.githubusercontent.com/1695496/61416085-68a29100-a8a7-11e9-96af-3d5cb6a6dd93.png)

**Comment by jbednar** [comment]
To me, viridis and viridis-like colors are problematic because matplotlib defaults to the non-reversed version, where the largest values are those most similar to the background.  Because people expect viridis to be in this order, even though it's incorrect as can be seen above (e.g. in the hextiles), I think we should choose a different one.  Same goes for fire and related maps -- people expect them to be in the non-reversed order, which is even worse for fire because the non-reversed one actually represents the color sequence from black-body radiation, and thus reversing it is very odd. Gray can be in any order, but it's always going to overlap in color with plot elements (axes, annotations, etc.) unless we limit to a very small range of medium grays, which will limit dynamic range.

So my own vote, grudgingly, is for kbc_r, which fits all the criteria and I don't think it has any natural preferred order that people expect.

**Comment by jbednar** [comment]
BTW, I just watched a live talk where someone used Viridis in the wrong order, which applies to almost every use of viridis I see.  The default ordering is only ever correct for plots with no background visible, which happens but is relatively rare.

**Comment by poplarShift** [comment]
Spacey, I love it!

Anyway, I can confirm; I used `bgy_r` for almost all figures of a talk a few months back, and people were very determined I used it the "wrong" way. I'm not sure I'd go as far as calling the standard use of viridis "wrong" either (bright colours close to red do appear more drastic I guess) but your mileage advocating for one or the other may vary...

**Comment by jbednar** [comment]
Right; people's expectations are a big problem. Viridis (and the other 3 main mpl uniform colormaps) is totally in the right order for a black background; the problem is just that Jupyter and PDF backgrounds are nearly always white, giving very unsuitable results.

BTW, anyone can propose another possible colormap here, and I'll run that notebook on it (or you can run it yourself and paste the resulting .png).

**Comment by jbednar** [comment]
Also note that the default annotation color is blue, which doesn't pop out against kbc as much as against fire, but it's still distinguishable and also kind of fits the theme:

![image](https://user-images.githubusercontent.com/1695496/61419336-a6f17d80-a8b2-11e9-9c1c-531a8dba53bc.png)

**Comment by philippjfr** [comment]
I think fighting against people's expectations is seriously problematic. It's definitely inarguable that non-reversed colormaps against a white background are problematic because it makes it hard to distinguish them from the background, but I also definitely wouldn't say they are **wrong**. The possibility that people will completely confuse the upper and lower bound, is imo something that we should not discount and has potentially much greater implications for misinterpreting data. People are used to dark to light color scales, for better or for worse, and I'm still severely hesitant using a default that subverts those expectations.

**Comment by jbednar** [comment]
Somehow all of science seems to have gotten confused, but I am very reluctant to go along with their confusion. I'm embarrassed on behalf of scientists everywhere!

I do very strongly assert that non-reversed colormaps are in fact wrong (incorrect and inappropriate) to use against a white background, because (a) people have to fight their own visual systems to interpret them correctly, and (b) people have a large danger of missing the most salient values, and (c) such plots only work at all because of properties of *typical* data, which makes them fall down for *atypical* data and outliers.

Consider kbc vs. kbc_r, for this plot of a 2D normal distribution on a white background:

![image](https://user-images.githubusercontent.com/1695496/61423803-09a04480-a8c6-11e9-863e-164ececcc934.png)

1. kbc highlights the very low-count cells around the edges, which with a non-reversed colormap are extremely salient to the visual system but of absolutely no scientific interest in normal cases -- that's just the noise floor of this measurement, not the data you are trying to measure at all! Those noisy patterns completely detract from the actual signal, making even quite different central regions look about the same because they are all always surrounded by noise.
2. For kbc_r, the center of the distribution, i.e. the highest count regions, are what pop out across the page, which is where most of the data is and the strongest signal is.  The light-blue regions are just noise, poorly sampled and thus with a shape that is of very little consequence, and so it is suitable that they are perceptually de-emphasized (but still detectable).
3. What would happen if there were a bug in this experiment and one particular cell along the margins happened to have highly anomalous values, as strong as the biggest peak of the data? E.g. if -2,-2 had a value of 25? 
   - For kbc_r, it is very unlikely that anyone would ever notice the bug, because it would be a very weakly colored spot in the midst of a bunch of very darkly colored spots and white spots. Worse, the more anomalous the result, both in value and in how far out it is, the *less* salient it would be.
   - For kbc such a bug (or momentous discovery!) would jump out immediately, being much darker both than its neighbors and the surrounding white page.  The more anomalous the value, the *more* salient it would be, as appropriate.
4. Conversely, what would happen if there were the opposite bug, with missing data (NaN) near the center of this distribution?
   - For kbc_r, almost no one would notice that problem or make that discovery either, because the white pixel would be very similar to its very light blue neighbors. Only someone specifically looking for that would notice it.
   - For kbc, the missing data would jump out immediately, in contrast to the very dark neighbors.

Given all this, why would anyone ever use kbc_r or other similar colormaps against white?  Well, (a) because it's the default (currently completely inappropriately but perhaps appropriately back when people used black-background monitors and presentation slides), and (b) they can still see the shape of the high-count regions because of the typically normal distribution of data values -- gradual shift from low counts to high counts, with high counts clustered spatially.  

I.e., it's possible to get an understanding of the data out of the "wrong" plot, but it's a very dangerous thing to do, because any of the less-common cases above *could* occur without anyone realizing it.  The point of a visualization is to *reveal* the data, not to paint a picture of what you already expect based on previous typical examples.  If a visualization reveals the typical  case ok but is completely misleading in atypical cases, it's a demonstrably incorrect thing to do, if there's another alternative that doesn't have that problem.

As shown above, reversing viridis or fire would fix the problem, but causes another problem with people's now completely trained bogus expectations. I don't think kbc suffers from those expectations; as a less familiar colormap, I think people will look at the colorbar if they are confused.

**Comment by jbednar** [comment]
Turns out it's easy enough to demonstrate problems 3 and 4 directly:

![image](https://user-images.githubusercontent.com/1695496/61426484-68b68700-a8cf-11e9-84e1-db9de1739efd.png)

Fun game -- try to spot the outlier at 2,2, which at a count of 32 should be the highest value in this plot.  Same goes for the hole at 0,0. Still think it's ok to use  kbc or  similarly inappropriate maps like viridis and fire, when the white background is visible?

**Comment by jbednar** [comment]
And of course the opposite is true for a black background, with kbc being the one to convey it accurately:

```
hex_tiles.options(opts.HexTiles(width=300, height=250, bgcolor="black", colorbar=True, cmap="kbc")) + \
hex_tiles.options(opts.HexTiles(width=300, height=250, bgcolor="black", colorbar=True, cmap="kbc_r"))
```

![image](https://user-images.githubusercontent.com/1695496/61428674-044bf580-a8d8-11e9-955a-6a3c4d1e1fcc.png)

**Comment by jbednar** [comment]
Plus, the problems don't get any better with more data, as there will always be some edge of the data that becomes ambiguous:

```
np.random.seed(44)
a = np.random.randn(50000, 2)
v = 0.12
a[np.logical_and(np.logical_and(a[:,0]>-v, a[:,0]<v),
                 np.logical_and(a[:,1]>-v, a[:,1]<v))] -= 2.82
hex_tiles = hv.HexTiles(a)

hex_tiles.options(opts.HexTiles(width=300, height=250, colorbar=True, cmap="kbc")) + \
hex_tiles.options(opts.HexTiles(width=300, height=250, colorbar=True, cmap="kbc_r"))
```
![image](https://user-images.githubusercontent.com/1695496/61429773-6a3a7c00-a8dc-11e9-86fe-2d8f3d07d7d0.png)

```
hex_tiles.options(opts.HexTiles(width=300, height=250, bgcolor="black", colorbar=True, cmap="kbc")) + \
hex_tiles.options(opts.HexTiles(width=300, height=250, bgcolor="black", colorbar=True, cmap="kbc_r"))
```
![image](https://user-images.githubusercontent.com/1695496/61429792-7c1c1f00-a8dc-11e9-9684-c3e0cee9b0d7.png)

**Comment by jbednar** [comment]
As discussed in https://github.com/holoviz/holoviews/pull/4567, there are now many reasons to change the default colormap.  I'm again convinced by my diatribe above that kbc_r is our best option for a colormap.  It's perceptually uniform, appropriate for a white background, is not typically used widely and thus has no expected ordering, is completely different from the default so that people cannot fail to notice the change (compared to just flipping the fire order and deleting white), is compatible with the other default colors in HoloViews, is already the default in hvPlot, and looks pretty good to me. 

What does it take to make it the default?  Presumably copy kbc to holoviews/plotting/util.py alongside fire, add kbc_r, and update these references?

```
./plotting/bokeh/__init__.py:178: options.Spikes = Options('style', color='black', cmap='fire', muted_alpha=0.2)
./plotting/bokeh/__init__.py:161: dflt_cmap = 'fire'
./plotting/plotly/__init__.py:103: dflt_cmap = 'fire'
./plotting/mpl/__init__.py:223: dflt_cmap = 'fire'
./plotting/mpl/__init__.py:240: options.Surface = Options('style', cmap='fire')
./plotting/mpl/__init__.py:241: options.Spikes = Options('style', color='black', cmap='fire')
```

**Comment by jbednar** [comment]
Default was changed to kbc_r in HoloViews 1.14.0.
