### ISSUE TITLE
Text backend?

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviews#410]
For automated testing and to ensure that the core HoloViews code doesn't depend on any plotting libraries, it would be nice to be able to select a "text" or "ascii" backend, which would without any warnings just print reprs() of all graphical objects, but still allow indexing to get numerical values out after selection and summary operations, and would print tables as text.  I.e., it should run precisely the same code as all other backends, producing the same numerical and textual results, without any graphical results.  I think this would be really useful for (a) showing off the core data-processing functionality of HoloViews, (b) allowing automated testing that numerical results don't change, and (c) letting users run and export their notebooks even on systems with no plotting library installed, while still seeing useful debugging output along the way.

**Comment by jlstevens** [comment]
One thing I have considered is generating HTML tables because these would be must quicker to render than with matplotlib. This wouldn't require any plotting backend but it wouldn't work well with HoloMaps. We could consider generating truncated HTML tables for most element types. 

Other than this, I'm not sure how useful a purely textual representations will be in practice. The current reprs work fairly well I think but they aren't designed to convey information about any numerical values.

**Comment by jbednar** [comment]
That's good idea; something like what Pandas and Numpy does for large tables would be a useful textual representation, and would allow at least some level of testing.

**Comment by philippjfr** [comment]
I'm -1 on this and would like to close this. I think there is significant cost to keeping open issues that will never be addressed.

**Comment by jbednar** [comment]
I don't mind closing it, but I do think this will come up again once holoviews has been split into core and plotting backends...
