### ISSUE TITLE
glaciers app broken on master

### ISSUE THREAD

**Issue by jonmmease** [holoviz/holoviews#4116]
I haven't been able to track it down, but there seems to be a problem with the glaciers demo (https://github.com/pyviz-topics/examples/tree/master/glaciers) on master (as of 93294f38c0cad0e9bbaf24952d98e15a2f55aa42). It works fine with latest release (1.12.7).

The notebook displays the following warning (which is not present with 1.12.7):
![Screenshot_20191203_084646](https://user-images.githubusercontent.com/15064365/70056430-72eccf80-15a9-11ea-805f-21f932a3d284.png)

And the datashader overlay isn't showing up

![Screenshot_20191203_084817](https://user-images.githubusercontent.com/15064365/70056563-a9c2e580-15a9-11ea-9250-7dc732d61538.png)

**Comment by jbednar** [comment]
@jlstevens , that warning sounds related to your rasterize changes.

**Comment by jbednar** [comment]
The warnings are caused by `datashade` inheriting from both `rasterize` and `shade` while sharing the same arguments; previously HoloViews and Param had been silent about unused arguments, but now the fact that `shade` is consuming `cmap` is not known by `rasterize`.  @jlstevens will look into what to do about that, but in the meantime, the warning can be avoided by replacing `datashade(elem, ..., cmap=X)` with `shade(rasterize(elem, ...), cmap=X`.  I don't _think_ this explains anything about why the data is not showing up, though.

**Comment by jlstevens** [comment]
@jonmmease I can reproduce the warning but not the lack of datashaded output on current HoloViews master (1.13.0a13.post12+g605ba06d5):

![image](https://user-images.githubusercontent.com/890576/70352659-41863500-1831-11ea-8a79-03047bcfcc58.png)

**Comment by jlstevens** [comment]
Actually, I can reproduce when it comes to the final panel dashboard:

![image](https://user-images.githubusercontent.com/890576/70352810-9aee6400-1831-11ea-811a-21124ac10297.png)

Odd that the output no longer appears!

**Comment by jlstevens** [comment]
@jonmmease #4121 should fix the warning and @philippjfr has a fix for the datashaded output not showing up.

**Comment by jonmmease** [comment]
great, thanks!

**Comment by jlstevens** [comment]
@jonmmease My parameter warning fix has been merged and the annotators PR (which contains the fix for the datashader output not showing up) has also been merged. I think this PR can be closed now but maybe you would first like could confirm that this issue has now been addressed?

**Comment by jonmmease** [comment]
Thanks @jlstevens and @philippjfr, everything is working again on master. Closing
