### ISSUE TITLE
Numpy 1.18.1 causing issues (on hv.Chord)

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/holoviews#4223]
When using numpy 1.17.4 code example below doesn't cause an issue, but w**hen using numpy 1.18.1 this gives the following error:**
`TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.`

For complete error see also: https://stackoverflow.com/questions/60152293/error-running-holoview-example-of-chord-diagram

Example comes from: http://holoviews.org/gallery/demos/bokeh/route_chord.html

Following line gives the error:
```python
chord = hv.Chord((route_counts, nodes), ['SourceID', 'DestinationID'], ['Stops'])
```

Full code example:
``` python
import holoviews as hv
from holoviews import opts, dim
from bokeh.sampledata.airport_routes import routes, airports

hv.extension('bokeh')

# Count the routes between Airports
route_counts = routes.groupby(['SourceID', 'DestinationID']).Stops.count().reset_index()
nodes = hv.Dataset(airports, 'AirportID', 'City')
chord = hv.Chord((route_counts, nodes), ['SourceID', 'DestinationID'], ['Stops'])
```

Tested on:
holoviews                 1.12.7                     
pandas                    1.0.0           
numpy                     1.18.1           
bokeh                     1.4.0

**Comment by ceball** [comment]
From the numpy 1.18 release notes:
> np.linspace parameter num must be an integer. Deprecated in NumPy 1.12. (gh-14620)

```
$ python -Wd 
>>> import numpy as np
>>> np.__version__
'1.17.4'
>>> np.linspace(0,10,10.0)
<string>:6: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])
```

Talking about deprecation warnings (and similar) in general (and across holoviz), rather than this specific issue, I think this is the situation:
  * Many libraries (e.g. numpy) follow a well defined deprecation process and give plenty of time to deal with deprecations.
  * In general it's easy to check for deprecation warnings while running the test suite.
  * We haven't decided or implemented a good way to make such deprecation warnings visible.

I vaguely propose something like this:
  * Have CI check and report on deprecation warnings periodically (i.e. not be part of regular builds, as they are ok to have and don't need to be fixed straight away).
  * Make the above results visible ultimately as something like "good first issues" in github, as many are likely to be straightforward ways for people to join in and contribute to maintenance.

However, a proposal alone is not actually very helpful, sorry :( I guess I am hoping someone might figure out something good with github actions, or something like that. I guess even just displaying the warnings somewhere would be a good first step, although previous experience suggests that we might just ignore that :)

**Comment by SandervandenOord** [comment]
Oh, sorry, this issue is a duplicate of: https://github.com/holoviz/holoviews/issues/4209
But the discussion is valuable.
