### ISSUE TITLE
link_selections to support lasso

### ISSUE THREAD

**Issue by afonit** [holoviz/holoviews#4359]
Link selections are amazing especially when combined with datashader.

My do a lot of geographic datashader plots.  The areas we want to select don't usually fit within the Box Select.

This Feature Request is to add in the capability for **datashader link_selections to support Lasso**

For example, on this page: http://holoviews.org/user_guide/Linked_Brushing.html

There is this example:
![image](https://user-images.githubusercontent.com/1798497/78384304-f21a0080-75a7-11ea-9036-f0c2575a172c.png)

In addition to the box select it would be great to have lasso select as some projects may require more delicate/drawn shapes to be used rather than the square box select.

**Comment by jbednar** [comment]
Yes, lasso select would be fabulous, but it's quite tricky to support it. So that you see how it works, when you use a box select tool for a linked selection, an expression is generated like this:

`((dim('x') >= 0.1) & (dim('x') <= 5.5)) & (dim('y') >= 1.6)) & (dim('y') <= 9.8))`

This expression matches the box that you drew with the box-select tool, and it is then used to do a query on the original dataset, creating a new dataset consisting only of those points that fall into the specified range of x and y. Basically, all datapoints with x or y not in the indicated ranges are filtered out, and then the resulting smaller set of data points is datashaded.

To do the same thing for a lasso select tool would require constructing an expression for the lasso shape that could be used for such a query, which is much more difficult than for a square axis-aligned rectangle as in box select. What we would do is to first calculate the bounding box of the lassoed region, filter on that to reject most of the points, and then iterate through the remaining data points to test whether they fit into a polygonal approximation to the lasso, or maybe a rasterized (pixelated) version of the lasso, further rejecting those datapoints that are within the bounding box but not within the lassoed area.  We can certainly do that, but it's very tricky, and not something we're currently planning to attempt. 

For our own purposes, what we are doing instead is a poor approximation to rasterizing the lasso, which is to enable the "union" mode for selections, then draw multiple rectangular regions that together add up to the non-rectangular region we want to select:

![image](https://user-images.githubusercontent.com/1695496/78388762-2ccf6900-75a7-11ea-8a9b-23ce3885ee83.png)

**Comment by philippjfr** [comment]
To make this happen we need to handle it for both columnar and gridded data, in theory we have everything to make that happen:

* `Gridded`: In theory this could be as simple as `rasterize(hv.Polygons([lasso_polygon]), target=gridded_dataset)`
* `Columnar`: To this we need a spatial `contains` method, which I think we already have available in spatialpandas.

So I think this is actually pretty feasible.

**Comment by jbednar** [comment]
Did I hear a volunteer? :-)

**Comment by jbednar** [comment]
It looks like getting cool new features requires simply stating the problem and possible solutions clearly, then telling @philippjfr that it's very tricky to solve. :-). In this case Philipp realized that we had already done the hard work by adding polygon rasterization to [Datashader ](https://datashader.org)and point-in-polygon testing to [spatialpandas](https://github.com/holoviz/spatialpandas), and so precisely the operations we needed here were already available.  So it was a perfect time to ask this question!

**Comment by philippjfr** [comment]
Merged in #4362
