### ISSUE TITLE
Formatter function name can't start with capital letter

### ISSUE THREAD

**Issue by gioarma** [holoviz/holoviews#4394]
Found this weird bug, the title explains the problem. 
**holoviews version** : 1.13.1
 
Here's an example:
### Works
```python
def myformatter(value):
    return str(value) + ' %'

points = hv.Points(np.exp(np.linspace(0, 1)))
points.options(xformatter=myformatter, yformatter='$%.2f')
```
### Works (just changed the 'f' to capital)
```python
def myFormatter(value):
    return str(value) + ' %'

points.options(xformatter=myFormatter, yFormatter='$%.2f')
```

### Doesn't work (just changed the 'm' to capital)
```python
def Myformatter(value):
    return str(value) + ' %'

points.options(xformatter=Myformatter, yFormatter='$%.2f')
```

**AttributeError** `'NoneType' object has no attribute 'start`

**Comment by maximlt** [comment]
Hi @gioarma,

Thanks for reporting this bug. I've just opened a PR in ``pscript`` as it was caused by this package that seemed not to handle this case. Until this is fixed, try not to use uppercased functions ;) (see PEP8).

(Note that your last two examples do not work because you wrote ``yFormatter`` (with ``F``) instead of ``yformatter``)

**Comment by philippjfr** [comment]
Wow, thanks @maximlt!

**Comment by philippjfr** [comment]
I'll close, since there's nothing we can do about this.
