### ISSUE TITLE
DOCS: API Reference Manual - classes do not expand to reveal documentation when clicked.

### ISSUE THREAD

**Issue by norweeg** [holoviz/holoviews#4535]
Applies to all subpackage pages e.g. http://holoviews.org/reference_manual/holoviews.annotators.html

all page elements of class .py.class.rm_collapsed do not expand when clicked to reveal documentation rendering the API docs unusable/incomplete.  Affects current versions of Google Chrome and Mozilla Firefox at least and probably others.

what I expected:

![image](https://user-images.githubusercontent.com/5969754/88570896-d92bd400-d00a-11ea-95ee-531a177618cb.png)
the element expands when clicked, becoming .py.class.rm_expanded (screenshot taken after manually changing css class in chrome element inspector)

what actually happens:

![image](https://user-images.githubusercontent.com/5969754/88570757-9d910a00-d00a-11ea-80bf-7b6301db2c73.png)

no change.  clicking has no effect

**Comment by andrewrosss** [comment]
I've noticed this issue as well. I tried viewing the holoviews API docs on Chrome, Firefox, and Brave with the same results. 

I'm wondering if this issue is related to sphinx, or maybe some JS used by sphinx, because this same bug can be seen in the [nipype](https://nipype.readthedocs.io/en/latest/index.html) docs as well. For example on [this page](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.fsl.preprocess.html) the buttons/links on the right (as shown below) under "Table of Contents" are no longer clickable, but they used to be and I think they still should be base on the site's source code.

<img width="1552" alt="Screen Shot 2020-07-27 at 9 07 24 PM" src="https://user-images.githubusercontent.com/23389447/88607662-c686be80-d04d-11ea-882f-7b7d9b35dd27.png">

**Comment by philippjfr** [comment]
Oh wow thanks for catching that! That's pretty bad, taking a look now and hopefully fixing for 1.13.4.

**Comment by ceball** [comment]
Seems like something to fix in nbsite.

The class name `"class rm_collapsed"` is now apparently `"py class rm_collapsed"`, so nbsite's nbsite.js's `expand()` no longer works:

```js
function expand(e) {
        [...]
	if (p.className == "class rm_collapsed")
		p.className = "class rm_expanded";
	else if (p.className == "class rm_expanded")
		p.className = "class rm_collapsed";
}
```
(https://github.com/pyviz-dev/nbsite/blob/529c3743c5c33b26c4b3b07da6517d3e6f8a14e4/nbsite/_shared_static/nbsite.js#L1-L12)

Maybe we should change the test to be something like `p.classList.contains("rm_collapsed")`? But I have no idea how we arrived at this naming or what any of it means :)

**Comment by ceball** [comment]
https://github.com/pyviz-dev/nbsite/pull/172 maybe?

**Comment by philippjfr** [comment]
Thanks @ceball, fixed in https://github.com/pyviz-dev/nbsite/pull/172.
