### ISSUE TITLE
letters in front of plots – matplotlib

### ISSUE THREAD

**Issue by mullimanko** [holoviz/holoviews#4773]
When plotting bar plots or chord plots as layouts (e.g. chord1+chord2) with matplotlib as backend, letters (A, B, C,...) are placed in front of the plots. Is this intended? How can I hide these letters? I didn't find something about this in the documentation (http://holoviews.org/user_guide/Plotting_with_Matplotlib.html), would be nice if it could be explained there.  [Here](https://anaconda.org/thoth/holoviews-issues-with-bars-plots/notebook) is an example:
![grafik](https://user-images.githubusercontent.com/40831563/103379870-6b1e9800-4ae7-11eb-995d-79022f8f2b15.png)

**Comment by jbednar** [comment]
Those are intended; they are subfigure labels for use when publishing or discussing subfigures.  They used to be documented extensively when Matplotlib was the default backend, but when we switched to Bokeh for most of our examples, we probably lost that documentation since we've never supported subfigure labels in Bokeh.  You can control those labels using various options starting `sublabel`, e.g. `sublabel_format=""` to disable them. I'd love to see a PR explaining them at the spot you'd expect to see them explained in the docs!

**Comment by mullimanko** [comment]
Thank you for your explanation. I wrote my first PR as requested and I am not sure if I did it right, it's not completely clear to me – I'm new to github. If something went wrong, just write me a message.

**Comment by jlstevens** [comment]
The PR referenced above has been merged so I think this issue has been resolved. I'll close this issue now but I am happy to reopen if you think this is still confusing.
