### ISSUE TITLE
Please break down functions and unit test them

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviews#5525]
Hi

I am a first-time contributor to HoloViews. Looking at the code it is quite daunting. The functions are very long and very branched.

I believe a major issue with this code base is that unittests have simply not been added systematically. Which means there are a lot of very complex and very hard to unittest functions.

This makes it very hard for new contributors to get into.

To take a specific example lets look at `plot.py` and `_compute_group_range`.

- It has 8 arguments which is a lot.
- They are not typed, so I have no chance of knowing what types they are without a lot of background knowledge.
- The function itself is very close to 200 lines of code.
- The function contains lot of branches
- It changes the given parameters in place.
- The function has no docstring
- The function has no dedicated tests

This podcast about sqlite can be used as inspiration https://corecursive.com/066-sqlite-with-richard-hipp/. The inventor of sqllite spent one year working 60 hours a week to add unit tests for every branch not only in the code but in the underlying assembly code.

That made the project rock solid and they did not have a bug in 8 years or something like that.

In addition to unit tests, I believe a more systematic approach to testing the various backends is really needed.

**Comment by philippjfr** [comment]
Different parts of the codebase have quite different histories with highly variable code quality, architecture and testing coverage. I'd break HoloViews down into a few different areas:

- Core objects and data structures (mostly implemented in `core/dimension`, `core/ndmapping` and `core/spaces`): This was designed by Jean-Luc and I. They are reasonably well designed and tested with quite a few highly questionable naming and API decisions.
- Data interfaces (live in `core/data`): Almost exclusively written and designed by myself. Also reasonably well designed and tested (with the exception of specific ones such as Ibis), some small API warts (mainly because`.values` is significantly overloaded).
- Options system (`core/options`): IMO a terrible concept and design and probably one of the main warts behind HoloViews, however, highly stable and reasonably well tested.
- Plotting code (`plotting/bokeh`, `plotting/matplotlib` and `plotting/plotly`): Probably 90% architected by me as a fairly novice programmer and grad student spending anywhere between 40-80 hours a week. Badly designed, poorly tested, very hard to maintain and extend, however the core parts are very stable.

The specific method you are talking about, specifically `_compute_group_range` is indeed very ugly and not amenable to good unit testing but it is also highly, highly stable and indirectly tested through **hundreds** of integration tests. 

Overall I do not believe this issue adds anything. HoloViews has a ton of tech debt, development has largely stalled but the core parts are pretty stable. If we decide to invest more in HoloViews as a project that likely won't be done by incremental improvements but rather a much larger project to reimplement the plotting interfaces in a clean, extensible, and well documented form. In the meantime we could spend time on developer docs and architecture diagrams but that is well covered by other issues.

**Comment by philippjfr** [comment]
Also I very much appreciate your frustration with the codebase @MarcSkovMadsen , especially in the absence of reasonable design and developer docs.
