### ISSUE TITLE
opts Text (fontsize=....) ignored

### ISSUE THREAD

**Issue by vascotenner** [holoviz/holoviews#931]
The style options to set the fontsize is ignored:

```
%%opts Text (fontsize=....)
```

Does not change anything. This is regression of #260 

The current solution is different from the general approach of holoviews: separate content and style.

**Comment by jlstevens** [comment]
> The current solution is different from the general approach of holoviews: separate content and style.

That is an interesting point - the ``hv.Text`` element is a bit special in that regard because it is an annotation element. Annotation elements have existed as a separate category for a while and perhaps we should revisit their design: maybe ``fontsize`` ought to be a plot option but right now it isn't and that was an intentional decision that maybe we should reconsider.

**Comment by philippjfr** [comment]
So I don't think there's anything to do about this, fontsize is part of the element definition which is strange but has been like this since the beginning. `Labels` offers an alternative option with a more consistent API.
